# what language the build will be configured for
language: python

# specify what versions of python will be used
# note that all of the versions listed will be tried
python:
    - 3.6

git:
    submodules: false
    
# what branches should be evaluated
branches:
    only:
        - master

before_install:
    - echo "In before_install"

# list of commands to run to setup the environment
install:
    - pip install coverage
    - pip install coveralls
    - pip install -r requirements.txt

# the actual commands to run
script:
    - coverage run -m unittest discover

# generate a coverage report to send to back to user
after_success:
    - coverage report
    - coveralls
